Kravoversikt
navikt/grensekomp-frontend pull request #15
Opened 2021-04-12 11:24 UTC by MrFjellstad

2021-04-15 07:14 UTC, laukvik commented on src/api/refusjonskaravList/refusjonskravList.ts
> +import environment from '../../config/environment';
Det er stavefeil i mappenavnet.

2021-04-15 07:17 UTC, laukvik commented on src/components/felles/knapper/SlettKravKnapp/SlettKravKnapp.test.tsx
> +expect.extend(toHaveNoViolations);
I jest konfigurasjonen (setupTests.ts) ligger denne allerede og trenger ikke inkluderes i tester.

2021-04-15 07:18 UTC, laukvik commented on src/components/oversikt-krav/KravListe.tsx
> +            {props.innsendinger &&
Unødvendig sjekk på om props.innsendinger er satt. Arrayen er ikke optional

2021-04-15 07:20 UTC, laukvik commented on src/components/oversikt-krav/KravListe.tsx
> +                  <Lenke href='#' onClick={() => props.onKravClick(item)}>
InternLenke klassen kan brukes her

2021-04-15 07:22 UTC, laukvik commented on src/components/oversikt-krav/KravSammendrag.tsx
> +          <Lenke href='#' onClick={handleTilbake}>
Kan bruke InternLenke

2021-04-15 07:32 UTC, laukvik commented on src/components/oversikt-krav/mapOversiktKravValidationResponse.ts
> +  response: BulkValidationResponse,
Virker galt å bruke denne responsen. Kan du kommentere?

2021-04-15 07:33 UTC, laukvik commented on src/state/oversikt-krav/OversiktKravActions.ts
> +  Fnr,
Her er det vel en del som ikke er i bruk. Fra, til, dager, beløp og land. Kanskje flere

2021-04-15 07:34 UTC, laukvik commented on src/state/oversikt-krav/OversiktKravItem.ts
> +export enum RefusjonskravStatus {
Er det bedre om denne er i egen fil?

2021-04-15 12:42 UTC, laukvik commented on src/utils/formatIsoAsCountry.ts
> +const formatIsoAsCountry = (alpha3: string): string => {
Hardkodet til norge? Må være feil her...

2021-04-15 12:43 UTC, laukvik commented on src/state/oversikt-krav/unikeInnsendinger.ts
> +import OversiktKravItem from './OversiktKravItem';
Synes metoden burde være prefikset med et verb: finn, filter, find eller liknende.

2021-04-15 12:46 UTC, laukvik commented on src/state/oversikt-krav/OversiktKravReducer.ts
> +    case Actions.KravSelected:
Synes "Krav" er overflødig dersom man ikke kan gjøre andre Selection.

2021-04-15 12:47 UTC, laukvik commented on src/state/oversikt-krav/OversiktKravReducer.ts
> +      nextState.activtKrav = undefined;
activtKrav burde gjøres om til activeKrav eller aktivtKrav.

2021-04-15 12:49 UTC, laukvik commented on src/state/oversikt-krav/OversiktKravReducer.ts
> +        throw new Error('Du må spesifisere response');
Dersom backend feiler så må det bli feilmelding og ikke kaste Error.

2021-04-15 13:07 UTC, laukvik requested changes
Veldig bra. Noen hardkodinger som må vekk. Og noen forslag...

2021-04-16 07:37 UTC, MrFjellstad commented on src/utils/formatIsoAsCountry.ts
> +const formatIsoAsCountry = (alpha3: string): string => {
Filen skal slettes.

2021-04-16 07:39 UTC, MrFjellstad commented on src/state/oversikt-krav/OversiktKravReducer.ts
> +      nextState.activtKrav = undefined;
trøngelsk!

2021-04-16 13:14 UTC, closed without merging