Flere keys
navikt/grensekomp-frontend pull request #34
Opened 2021-04-27 14:41 UTC by jafeld

2021-04-28 07:02 UTC, laukvik commented on src/components/bulk/DagerHjelpeLabel.tsx
> +        Her teller du dagene det skulle vært utbetalt lønn fra og med dag 4 i arbeidsgiverperioden. Helger og
Ikke oversatt.

2021-04-28 07:03 UTC, laukvik commented on src/components/bulk/MaanedsinntektHjelpeLabel.tsx
> +            inntekter som kan tas med i beregningen
Ikke oversatt

2021-04-28 09:13 UTC, MrFjellstad commented on src/components/bulk/DagerHjelpeLabel.tsx
> +      <li>
Her kan det bli tull når vi ikke har <ul> rundt.

2021-04-30 13:31 UTC, laukvik commented on src/components/bulk/DagerHjelpeLabel.tsx
> +      <li>
Her kan du bruke Oversettelse komponentet

2021-04-30 13:32 UTC, laukvik commented on src/components/bulk/MaanedsinntektHjelpeLabel.tsx
> +            inntekter som kan tas med i beregningen
Her kan du bruke Oversettelse komponentet

2021-04-30 13:32 UTC, laukvik commented on src/components/login/LoggetUtAdvarsel.tsx
> +        <Innholdstittel>{t(Key.LOGGET_UT)}</Innholdstittel>
Her kan du bruke Oversettelse komponentet

2021-04-30 13:32 UTC, laukvik commented on src/components/oversikt-krav/KravListe.tsx
> +          {t(Key.TIDLIGERE_SØKT)}
Her kan du bruke Oversettelse komponentet

2021-05-03 13:38 UTC, MrFjellstad requested changes

2021-05-03 13:38 UTC, MrFjellstad commented on src/components/felles/RadNr.tsx
> +  return <div className={t(Key.ROW_NUMBER) + props.className ?? ''}>{props.nr}</div>;
Her har du oversatt et css klassenavn...

2021-05-03 13:39 UTC, MrFjellstad commented on src/locales/Oversettelse.tsx
> +bold: _ text -
bold: _text_

2021-05-03 13:45 UTC, laukvik commented on src/api/loginexpiry/LoginExpiryAPI.test.ts
> +    const mockApi = Promise.resolve({
Det fins en convenience metode til mocking for dette: mockFetch

2021-05-03 13:46 UTC, MrFjellstad requested changes

2021-05-03 13:46 UTC, MrFjellstad commented on src/components/oversikt-krav/KravListe.tsx
> +        <Innholdstittel className='kravliste-tittel'>Oversikt over tidligere innsendte krav</Innholdstittel>
Her mangler det en oversettelse

2021-05-03 13:46 UTC, MrFjellstad commented on src/components/kvittering/Kvittering.tsx
> +              <Lenke href='https://www.altinn.no'>Altinn</Lenke>.{t(Key.KONTAKT)}
Kunne brukt oversettelseskomponentet og hatt alt i et.

2021-05-03 13:46 UTC, laukvik commented on src/components/bulk/BeloepHjelpeLabel.tsx
> +      <span className='hjelpetekst-beskrivelse'>{t(Key.BEREGNET_INNTEKT)}</span>
Ble vi ikke enige om å prefikse med komponentnavn? BeloepHjelpeLabel_YOUR_KEY

2021-05-03 13:47 UTC, laukvik commented on src/components/bulk/Bostedland/Bostedland.test.tsx
> +
Fint at du lager tester

2021-05-03 13:50 UTC, laukvik commented on src/components/bulk/MaanedsinntektHjelpeLabel.tsx
> +      <Oversettelse langKey={Key.MAANEDSINNTEKTHJELPELABEL_INFO} />
HERBLIRDETVELDIGVANSKELIGÅLESENÅRDETIKKEFINNESNOENSEPARATORER.

2021-05-03 13:53 UTC, laukvik commented on src/components/felles/Feilmeldingspanel/Feilmeldingspanel.tsx
> +        <Feiloppsummering tittel={t(Key.FEILOPPSUMERING)} feil={props.feilmeldinger} />
Synes denne burde hete samme som komponent

2021-05-03 13:58 UTC, laukvik commented on src/components/oversikt-krav/KravListe.tsx
> +        <Innholdstittel className='kravliste-tittel'>Oversikt over tidligere innsendte krav</Innholdstittel>
Ikke oversatt

2021-05-03 14:02 UTC, laukvik commented on src/locales/Languages.ts
> +      `-- [Åpne ID-Porten (innlogging) i nytt vindu ved å klikke på denne lenken.](${injectRedirectPath(
Denne virker sketchy!

2021-05-03 14:04 UTC, laukvik requested changes
Mener å huske vi ble enige om å prefikse språk nøklene med navn på komponent. Dersom feilen ligger i KomponentXYX så og nøkkelen lokalt heter ERROR så skal nøklen hete "KomponentXYX_ERROR".

2021-05-03 14:39 UTC, jafeld commented on src/components/bulk/BeloepHjelpeLabel.tsx
> +      <span className='hjelpetekst-beskrivelse'>{t(Key.BEREGNET_INNTEKT)}</span>
Normalt, jo, men denne key er brukt i flere komponenter

2021-05-03 14:41 UTC, jafeld commented on src/components/felles/Feilmeldingspanel/Feilmeldingspanel.tsx
> +        <Feiloppsummering tittel={t(Key.FEILOPPSUMERING)} feil={props.feilmeldinger} />
Igjen en key som er brukt i flere komponenter

2021-05-03 14:42 UTC, jafeld commented on src/locales/Languages.ts
> +      `-- [Åpne ID-Porten (innlogging) i nytt vindu ved å klikke på denne lenken.](${injectRedirectPath(
Er presis det sammen som komponenten gjorde før

2021-05-03 14:42 UTC, jafeld commented on src/locales/Languages.ts
> +      `-- [Åpne ID-Porten (innlogging) i nytt vindu ved å klikke på denne lenken.](${injectRedirectPath(
Men ja, super sketchy metodenavn...

2021-05-05 06:44 UTC, MrFjellstad commented on src/locales/Oversettelse.tsx
> +link: [link name](link url)
emphasise: *text*

2021-05-05 06:44 UTC, MrFjellstad approved these changes

2021-05-05 08:02 UTC, merged